[project]
name = "fedbiomed"
version = "v5.2.2"
description = "Collaborative learning"
authors = [
    {name = "Sergen Cansiz", email = "sergen.cansiz@inria.fr"},
]
dependencies = [
    "tinydb ~=4.7.1",
    "tabulate >=0.9.0,<0.10.0",
    "psutil ~=5.9.0",
    "requests ~=2.29.0",
    "validators >=0.20.0,<0.21.0",
    "packaging ~=23.1",
    "cryptography ~=40.0.0",
    "pyopenssl ~=23.1.1",
    "joblib >=1.2.0,<1.3.0",
    "itk >=5.3.0,<5.4.0",
    "scipy >=1.10.0,<1.11.0",
    "scikit-learn >=1.2.0,<1.3.0",
    "torch >=2.0.0",
    "torchvision >=0.18.0,<0.19.0",
    #pytorch-ignite >=0.4.4,<0.5.0",
    "opacus >=1.4.0,<1.5.0",
    "monai >=1.1.0,<1.2.0",
    # other
    "msgpack ~=1.0",
    "persist-queue >=0.5.1,<0.6.0",
    # pandas 2.x recently released (2023-04) but few breaking changes
    "pandas ~=2.0.1",
    "python-minifier ~=2.9.0",
    # FLamby
    "flamby@git+https://github.com/owkin/FLamby",
    # declearn
    "declearn[torch] ~=2.3.2",
    #Secure aggregation
    "gmpy2 >=2.1,< 2.2",
    "grpcio ~=1.60.0",
    "grpcio-tools ~=1.60.0",
    "filedialpy>=1.2.0",
    "tk>=0.1.0",
]

requires-python = "<3.12,>=3.10"
readme = "README.md"
license = {text = "Apache 2.0"}

[tool.setuptools]
packages = ["fedbiomed", "fedbiomed.gui"]


[tool.setuptools.package-dir]
fedbiomed = "fedbiomed"
"fedbiomed.gui" = "gui"

[tool.setuptools.package-data]
"fedbiomed.gui" = ["ui/public/*.*"]




[tool.pdm]
distribution = true
[tool.pdm.dev-dependencies]
test = ["pytest", "pytest-cov"]
lint = ["flake8", "black"]
docs = [
	"mkdocs-material==9.5.18",
	"mkdocs-jupyter==0.24.1",
	"mkdocs-minify-plugin==0.6.4",
	"mkdocstrings-python==1.10.8",
]
dev = [
]

[project.scripts]
fedbiomed = "fedbiomed.cli:run"



[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

