[tool.poetry]
name = "fedbiomed"
version = "5.2.0"
description = "Collaborative learning framework"
authors = ["Sergen Cansiz <sergen.cansiz@inria.fr>"]
license = "Apache 2.0"
readme = "README.md"

packages = [
	{include = "fedbiomed", from = "."},
	{include = "gui/**/*.py", to = "fedbiomed/gui"}
]

include = [
	"gui/ui/public/*.*",
	"envs/common",
	"scripts",
	"docs"
]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
numpy = "~2.0.0"
jupyter = "~1.0.0"
ipython = "~8.13.2"
tinydb = "~4.7.1"
tabulate = ">=0.9.0,<0.10.0"
colorama = ">=0.4.6,<0.5"
psutil = "~5.9.0"
requests = "~2.29.0"
validators = ">=0.20.0,<0.21.0"
packaging = "~23.1"
cryptography = "~40.0.0"
pyopenssl = "~23.1.1"
joblib = ">=1.2.0,<1.3.0"
itk = "~5.4.0"
scikit-learn = "~1.5.0"
torch = "~2.4"
torchvision = "~0.19.0"
opacus = ">=1.4.0,<1.5.0"
monai = ">=1.1.0,<1.2.0"
msgpack = "~=1.0"
persist-queue = ">=0.5.1,<0.6.0"
pandas = "~2.2.1"
tensorboard = "~2.13.0"
python-minifier = "~2.9.0"
jupyter-contrib-nbextensions = ">=0.7.0,<0.8.0"
pathvalidate = "~3.0.0"
flamby = { git = "https://github.com/owkin/FLamby", branch = "main"}
declearn = { version = "~2.3.2", extras = ["torch2"] }
gmpy2 = ">=2.1,< 2.2"
grpcio = "~1.60"
grpcio-tools = "~1.60"
unet = ">=0.7.7,<0.8.0"
matplotlib = "^3.9.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pytest-cov = "^4.1.0"
black = "*"

[tool.poetry.group.gui.dependencies]
jsonschema= ">=4.17, <4.18"
gunicon = "~23.0"
Flask-JWT-Extended = ">=4.4.4,<4.5.0"


#[tool.peotry.group.docs.dependencies]


[tool.poetry.scripts]
fedbiomed = "fedbiomed.cli:run"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
